config/routes.rb
Ouyutao::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations => "admins/registrations", :passwords => "admins/passwords"} do
     match '/admins/sign_out' => "admins/sessions#destroy", :via => [:get, :post]
  end

  root 'home#index'

  resources :categories
  resources :products

  namespace :admin do 
    root to: "home#index"

    resources :categories do
      collection do 
        get 'get_attrs'
      end
    end
    resources :products 
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	extend ActsAsTree::Presentation

	 attr_accessible :name, :pic, :description, :parent_id

	 has_many :products

	 mount_uploader :pic, CategoryPicUploader
	 acts_as_tree order: "name"

	 def product_attrs
	 	 case self.name || self.parent.try(:name)
	 	 when "控制器"
	 	 	 return [{"轴数" => "zhou_num"},{"架构" => "arch"},{"支持数控CNC编程" => "cnc"},{"支持龙门同步方式" => "longmen"}, 
	 	 	 	{"支持GALVO整合" => "galvo"}, {"支持PLC功能" => "plc"}, {"现场总线类型" => "fieldbus"}, {"控制指令" => "control"}]
	 	 when "驱动器"
	 	   return [{"输出指令" => "output_instr"},{"持续电流" => "electricity"},{"支持电压" => "voltage"},{"支持现场总线类型" => "driver_fieldbus"}]	 
	 	 when "电机"  
	 	 	 return [{"电机类型" => "motor"},{"直线电机推力范围" => "linear_motor_range"},{"旋转电机类型" => "rotary_motor"},
	 	 	 	{"旋转电机持续扭矩范围" => "rotary_motor_range"}, {"特殊应用" => "special_ap"}]	 
	 	 when "执行器"
	 	   return [{"推力范围" => "thrust_range"}]	 	 	
	 	 when "滑台和直线单元"
	 	   return [{"驱动形式" => "driver"}, {"导向形式" => "oriented_form"}, {"特殊应用" => "slip_special_ap"}]	 	 	  
	 	 when "高精密定位平台"
	 	   return [{"运动类型" => "sports"}, {"驱动类型" => "driver_type"}, {"轴承类型" => "bearing"}, {"最大负载" => "max_load"}, {"高精纳米推荐" => "nano_recommend"}]	 	 	    
	 	 when "减速机"
	 	   return [{"精度" => "precision"}, {"减速比" => "reduction_ratio"}]	 	 	      
	 	 when "测量反馈装置"
	 	   return [{"运动形式" => "sports_type"}]	 	 	        
	 	 end
	 end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to :action => :index
    else  
      render :action => :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to :action => :index
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy if @category.present?

    redirect_to :action => :index
  end

  def get_attrs
    @product = Product.find_by(id: params[:product_id])
    @category = @product.present? ? @product.category : Category.find(params[:category_id])

    @attrs = @category.product_attrs if @category.present?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
    @products = @category.products
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params[:category]
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="grid_order">
  <tbody>
    <tr>
      <td width="10%">名称:</td>
      <td width="50%"><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td width="10%">图片:</td>
      <td width="50%"><%= f.file_field :pic %></td>
    </tr>
    <tr>
      <td width="10%">父类型:</td>
      <td width="50%"><%= f.select :parent_id, Category.all.map {|x| [x.name, x.id] }, {include_blank: ''} %></td>
    </tr>
    <tr>
      <td width="10%">描述:</td>
      <td width="50%"><%= f.kindeditor :description, :window_onload => true %></td>
    </tr>
    <tr>
      <td width="10%"></td>
      <td width="50%"><%= f.submit "提交" %></td>
    </tr>
   </tbody>
  </table>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

app/views/admin/categories/get_attrs.js.erb
<% if @product.present? %>	
$("#extend_attrs").html("<% @attrs.each do |attr| %><tr><% attr.each do |k,v| %><td><%= k %></td><td><select name='product[<%=v%>]'><options><% eval('Product.get_'+v+'_values').each do |key| %><option value='<%= key[1] %>' <%= 'selected' if eval('@product.'+v) == key[1] %>><%= key[0] %></option><% end %></options></select></td><% end %></tr><% end %>")
<% else %>
$("#extend_attrs").html("<% @attrs.each do |attr| %><tr><% attr.each do |k,v| %><td><%= k %></td><td><select name='product[<%=v%>]'><options><% eval('Product.get_'+v+'_values').each do |key| %><option value='<%= key[1] %>'><%= key[0] %></option><% end %></options></select></td><% end %></tr><% end %>")
<% end %>

app/views/admin/categories/index.html.erb
<table class="grid">
    <thead>
      <tr>
        <th width="10%">名称</th>
        <th width="10%">管理</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <%unless category.blank? %>
            <td width="10%"><%= category.name %></td>
            <td width="10%">
              <%= link_to "修改", edit_admin_category_path(category) %>&nbsp;&nbsp;
              <%= link_to "删除", admin_category_path(category), :method => :delete, confirm: "确认要删除该分类？" %>
            </td>
          <%else%>
            <td width="80%">
              <span style="color:red;"> 呀！有空对象啊！</span>
            </td>
          <%end%>
        </tr>
      <% end -%>
      <% if @categories.blank? %>
        <tr>
          <td colspan="6">暂无相关数据</td>
        </tr>
      <% end -%>
    </tbody>
</table>
<%#= will_paginate @categories %>

app/views/admin/categories/new.html.erb
<%= render 'form' %>