config/routes.rb
Ouyutao::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => "admins/sessions", :registrations => "admins/registrations", :passwords => "admins/passwords"} do
     match '/admins/sign_out' => "admins/sessions#destroy", :via => [:get, :post]
  end

  root 'home#index'

  resources :categories
  resources :products

  namespace :admin do 
    root to: "home#index"

    resources :categories do
      collection do 
        get 'get_attrs'
      end
    end
    resources :products 
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	extend ActsAsTree::Presentation

	 attr_accessible :name, :pic, :description, :parent_id

	 has_many :products

	 mount_uploader :pic, CategoryPicUploader
	 acts_as_tree order: "name"

	 def product_attrs
	 	 case self.name || self.parent.try(:name)
	 	 when "控制器"
	 	 	 return [{"轴数" => "zhou_num"},{"架构" => "arch"},{"支持数控CNC编程" => "cnc"},{"支持龙门同步方式" => "longmen"}, 
	 	 	 	{"支持GALVO整合" => "galvo"}, {"支持PLC功能" => "plc"}, {"现场总线类型" => "fieldbus"}, {"控制指令" => "control"}]
	 	 when "驱动器"
	 	   return [{"输出指令" => "output_instr"},{"持续电流" => "electricity"},{"支持电压" => "voltage"},{"支持现场总线类型" => "driver_fieldbus"}]	 
	 	 when "电机"  
	 	 	 return [{"电机类型" => "motor"},{"直线电机推力范围" => "linear_motor_range"},{"旋转电机类型" => "rotary_motor"},
	 	 	 	{"旋转电机持续扭矩范围" => "rotary_motor_range"}, {"特殊应用" => "special_ap"}]	 
	 	 when "执行器"
	 	   return [{"推力范围" => "thrust_range"}]	 	 	
	 	 when "滑台和直线单元"
	 	   return [{"驱动形式" => "driver"}, {"导向形式" => "oriented_form"}, {"特殊应用" => "slip_special_ap"}]	 	 	  
	 	 when "高精密定位平台"
	 	   return [{"运动类型" => "sports"}, {"驱动类型" => "driver_type"}, {"轴承类型" => "bearing"}, {"最大负载" => "max_load"}, {"高精纳米推荐" => "nano_recommend"}]	 	 	    
	 	 when "减速机"
	 	   return [{"精度" => "precision"}, {"减速比" => "reduction_ratio"}]	 	 	      
	 	 when "测量反馈装置"
	 	   return [{"运动形式" => "sports_type"}]	 	 	        
	 	 end
	 end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to :action => :index
    else  
      render :action => :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to :action => :index
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy if @category.present?

    redirect_to :action => :index
  end

  def get_attrs
    @product = Product.find_by(id: params[:product_id])
    @category = @product.present? ? @product.category : Category.find(params[:category_id])

    @attrs = @category.product_attrs if @category.present?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
    @products = @category.products
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params[:category]
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="main" class="productcategory">
        
    <form method="post" action="stages.aspx" id="aspnetForm">
<div>
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="">
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="">
<input type="hidden" name="__LASTFOCUS" id="__LASTFOCUS" value="">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUENTM4MQ9kFgJmD2QWAmYPZBYCAgYPZBYCAgEPZBYGAgIPEA8WAh4LXyFEYXRhQm91bmRnZBAVAwIyMAI1MAMxMDAVAwIyMAI1MAMxMDAUKwMDZ2dnFgFmZAIHDxAPFgIfAGdkEBUDAjIwAjUwAzEwMBUDAjIwAjUwAzEwMBQrAwNnZ2cWAWZkAgwPZBYCAgMPZBYKZg8PFgIeB1Zpc2libGVnZGQCAQ8PFgIfAWdkZAICDw8WAh8BZ2RkAgMPDxYCHwFnZGQCBA8PFgIfAWdkZGTYgX2VVc6FUWdrYsDmbEgcY8ZDlg==">
</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>


  <div id="content">
    <header id="main-header">
      <hgroup>
        <h1 id="page-title"><%= @category.name %></h1>
      </hgroup>
      <%= image_tag @category.pic.url, class: "billboard-image" %>
      <p><%= @category.description %></p>
    </header>
    <ul id="product-list">
      <% @products.each do |product| %>
      <li class="left" data-nid="1099">
        <article>
          <figure>
            <%= link_to image_tag("#{product.pic.url}", width: "178", height: "130"),  product_path(product) %>
          </figure>
          <header>
              <%= link_to "#{product.name}", product_path(product) %>
              </h1>
          </header>
          <p class="summary">
              <%= truncate product.description, length: 75, omission: '...' %> <%= link_to "More", product_path(product), class: 'more-link' %>
          </p>
        </article>
      </li>
      <% end %>
    </ul>
        
<div id="quickspec" style="left: -9999em; top: -9999em;"><h2></h2><div class="content"></div><a href="#" class="quickspec-more">Learn more about this product&nbsp;»</a><div class="arrow"></div></div></div>
<aside id="sidebar-first" class="facet-nav">
    <h1>Faceted Navigation</h1>
    
      
      <section class="applied-facets">
        <h1>You've Selected</h1>
        <ul>
          
    <li class="facet-1-0"><a class="remove-facet" href="/product-catalog.aspx" title="remove">(x)</a> Stages</li>

        </ul>
        <a href="/product-catalog.aspx" class="clear-all">
          Clear all selections
        </a>
      </section>
    
    
    
      <section class="unapplied-facets">
        <h1>Narrow Your Results</h1>
        <ul>
          

<li>
  <section id="motion-type-filter">
    <h2 class="filter-name">Motion Type</h2>
    <ul>
        
        
                <li><a href="/product-catalog/stages/linear-stage.aspx">Linear Stages <span class="facet-count">(41)</span></a></li>
        
                <li><a href="/product-catalog/stages/rotary-stage.aspx">Rotary Stages <span class="facet-count">(23)</span></a></li>
        
                <li><a href="/product-catalog/stages/linear-x-y-stages.aspx">Linear X-Y Stages <span class="facet-count">(12)</span></a></li>
        
                <li><a href="/product-catalog/stages/lift-and-z-axis-stages.aspx">Lift and Z-Axis Stages <span class="facet-count">(12)</span></a></li>
        
                <li><a href="/product-catalog/stages/manual-positioners.aspx">Manual Positioners <span class="facet-count">(3)</span></a></li>
        
    </ul>
  </section>
</li>

<li>
  <section id="drive-type-filter">
    <h2 class="filter-name">Drive Type</h2>
    <ul>
        
        
                <li><a href="/product-catalog/stages.aspx?drivetype=Direct">Direct <span class="facet-count">(59)</span></a></li>
        
                <li><a href="/product-catalog/stages.aspx?drivetype=Gear">Gear <span class="facet-count">(2)</span></a></li>
        
                <li><a href="/product-catalog/stages.aspx?drivetype=Manual">Manual <span class="facet-count">(3)</span></a></li>
        
                <li><a href="/product-catalog/stages.aspx?drivetype=Screw">Screw <span class="facet-count">(26)</span></a></li>
        
    </ul>
  </section>
</li>

<li>
  <section id="bearing-type-filter">
    <h2 class="filter-name">Bearing Type</h2>
    <ul>
        
        
                <li><a href="/product-catalog/stages.aspx?bearingType=Air">Air <span class="facet-count">(16)</span></a></li>
        
                <li><a href="/product-catalog/stages.aspx?bearingType=Mechanical">Mechanical <span class="facet-count">(74)</span></a></li>
        
    </ul>
  </section>
</li>
<li>
  <section id="maximum-load-filter">
  <h2 class="filter-name">Maximum Load</h2>
  <ul>
      
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=0">
      0–10&nbsp;kg
      
      (20)
      </a>
    </li>
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=1">
      11–20&nbsp;kg
      
      (22)
      </a>
    </li>
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=2">
      21–50&nbsp;kg
      
      (34)
      </a>
    </li>
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=3">
      51–100&nbsp;kg
      
      (15)
      </a>
    </li>
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=4">
      101–150&nbsp;kg
      
      (18)
      </a>
    </li>
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=5">
      151–450&nbsp;kg
      
      (7)
      </a>
    </li>
      
    <li>
      <a href="/product-catalog/stages.aspx?maxload=6">
      more than&nbsp;451&nbsp;kg
      
      (1)
      </a>
    </li>
      
  </ul>
  </section>
</li>


<li>
  <section id="application-filter">
    <h2 class="filter-name">Application</h2>
    <ul>
        
        
                <li><a href="/product-catalog/stages.aspx?application=Nanopositioning">Nanopositioning <span class="facet-count">(12)</span></a></li>
        
    </ul>
  </section>
</li>
        </ul>
      </section>
    
    
</aside>
</form>

        
      </div>